# SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import asyncio
import os
from pathlib import Path
from typing import List

from .base import EmbeddingModel


def get_executor():
    from . import embeddings_executor

    return embeddings_executor


class FastEmbedEmbeddingModel(EmbeddingModel):
    """Embedding model using FastEmbed.

    This class represents an embedding model that utilizes the FastEmbed library
    for generating sentence embeddings.

    Args:
        embedding_model (str): The name or path of the pre-trained model.

    Attributes:
        model: The model used for encoding sentences.
        embedding_size: The dimensionality of the sentence embeddings generated by the model.
    """

    engine_name = "FastEmbed"

    def __init__(self, embedding_model: str, **kwargs):
        from fastembed import TextEmbedding as Embedding

        # Enabling a short form model name for all-MiniLM-L6-v2.
        if embedding_model == "all-MiniLM-L6-v2":
            embedding_model = "sentence-transformers/all-MiniLM-L6-v2"
        self.embedding_model = embedding_model

        # If a pre-downloaded model exists in the cache, pass its path directly
        # to skip all download attempts. This avoids network calls in disconnected
        # environments where fastembed would otherwise try HuggingFace Hub and GCS.
        # See https://github.com/qdrant/fastembed/pull/614
        if "specific_model_path" not in kwargs:
            cached_path = self._find_cached_model(embedding_model, Embedding)
            if cached_path:
                kwargs["specific_model_path"] = str(cached_path)

        try:
            self.model = Embedding(embedding_model, **kwargs)
        except ValueError as ex:
            # Sometimes the cached model in the temporary folder gets removed,
            # but the folder still exists, which causes an error. In this case,
            # we fall back to an explicit cache directory.
            if "Could not find model.onnx in" in str(ex):
                self.model = Embedding(embedding_model, cache_dir=".cache", **kwargs)
            else:
                raise ex

        # Get the embedding dimension of the model
        self.embedding_size = len(list(self.model.embed("test"))[0].tolist())

    @staticmethod
    def _find_cached_model(embedding_model: str, embedding_cls) -> Path | None:
        """Find a pre-downloaded model in the fastembed cache.

        Looks up the HF source repo for the model in fastembed's registry,
        then checks if it exists in the HF-convention cache directory
        (models--{org}--{repo}/snapshots/{hash}/).
        """
        cache_dir = Path(os.environ.get("FASTEMBED_CACHE_PATH", str(Path.home() / ".cache" / "fastembed")))
        if not cache_dir.is_dir():
            return None

        for model_desc in embedding_cls.list_supported_models():
            if model_desc["model"] != embedding_model:
                continue
            hf_source = (model_desc.get("sources") or {}).get("hf")
            if not hf_source:
                break
            snapshots_dir = cache_dir / f"models--{hf_source.replace('/', '--')}" / "snapshots"
            if not snapshots_dir.is_dir():
                break
            snapshot_dirs = [d for d in snapshots_dir.iterdir() if d.is_dir()]
            if snapshot_dirs:
                return snapshot_dirs[0]
            break

        return None

    async def encode_async(self, documents: List[str]) -> List[List[float]]:
        """Encode a list of documents into their corresponding sentence embeddings.

        Args:
            documents (List[str]): The list of documents to be encoded.

        Returns:
            List[List[float]]: The list of sentence embeddings, where each embedding is a list of floats.
        """

        loop = asyncio.get_running_loop()
        result = await loop.run_in_executor(get_executor(), self.model.embed, documents)

        return [x.tolist() for x in result]

    def encode(self, documents: List[str]) -> List[List[float]]:
        """Encode a list of documents into their corresponding sentence embeddings.

        Args:
            documents (List[str]): The list of documents to be encoded.

        Returns:
            List[List[float]]: The list of sentence embeddings, where each embedding is a list of floats.
        """
        return [x.tolist() for x in self.model.embed(documents)]
