apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/opendatahub-io/NeMo-Guardrails?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "develop"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: opendatahub-release
    appstudio.openshift.io/component: odh-trustyai-nemo-guardrails-serve
    pipelines.appstudio.openshift.io/type: build
  name: odh-trustyai-nemo-guardrails-server-release-on-push
  namespace: open-data-hub-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/opendatahub/odh-trustyai-nemo-guardrails-server:latest
  - name: dockerfile
    value: Dockerfile.server
  - name: path-context
    value: .
  - name: build-platforms
    value:
    - linux/x86_64
    - linux-m2xlarge/arm64
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/opendatahub-io/odh-konflux-central.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipeline/multi-arch-container-build.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-odh-trustyai-nemo-guardrails-serve
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
