name: Develop Coverage

on:
  push:
    branches:
      - develop
    paths-ignore:
      - "**/*.md"

permissions:
  contents: read

jobs:
  develop-coverage:
    uses: ./.github/workflows/_test.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      os: Ubuntu
      image: ubuntu-latest
      python-version: "3.11"
      with-coverage: true
